# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d5d916b270d881f6b901636c675dacb"
name = "analytics-suite"
handle = "analytics-suite"
application_url = "https://apply-millions-lift-toner.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://apply-millions-lift-toner.trycloudflare.com/auth/callback",
  "https://apply-millions-lift-toner.trycloudflare.com/auth/shopify/callback",
  "https://apply-millions-lift-toner.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
